#define SHIFT_DATA 2
#define SHIFT_CLK 3
#define SHIFT_LATCH 4
#define EEPROM_D0 5
#define EEPROM_D7 12
#define EEPROM_CE_ 13
#define EEPROM_WE_ PIN_A0

/*
 * Output the address bits and outputEnable signal using shift registers.
 */
void setAddress(int address, bool outputEnable) {
  shiftOut(SHIFT_DATA, SHIFT_CLK, MSBFIRST, (address >> 8) | (outputEnable ? 0x00 : 0x80));
  shiftOut(SHIFT_DATA, SHIFT_CLK, MSBFIRST, address);

  digitalWrite(SHIFT_LATCH, LOW);
  digitalWrite(SHIFT_LATCH, HIGH);
  digitalWrite(SHIFT_LATCH, LOW);
}


/*
 * Read a byte from the EEPROM at the specified address.
 */
byte readEEPROM(int address) {
  for (int pin = EEPROM_D0; pin <= EEPROM_D7; pin += 1) {
    pinMode(pin, INPUT_PULLUP);
  }
 digitalWrite(EEPROM_CE_, LOW);
 setAddress(address, /*outputEnable*/ true);
 
  byte data = 0;
  for (int pin = EEPROM_D7; pin >= EEPROM_D0; pin -= 1) {
    data = (data << 1) + digitalRead(pin);
  }
  digitalWrite(EEPROM_CE_, HIGH);

  return data;
}



/*
 * Write a byte to the EEPROM at the specified address.
 */
void writeEEPROM(int address, byte data) {
  digitalWrite(EEPROM_CE_, LOW);

  setAddress(address, /*outputEnable*/ false);
  for (int pin = EEPROM_D0; pin <= EEPROM_D7; pin += 1) {
    pinMode(pin, OUTPUT);
  }

  for (int pin = EEPROM_D0; pin <= EEPROM_D7; pin += 1) {
    digitalWrite(pin, data & 1);
    data = data >> 1;
  }
  digitalWrite(EEPROM_WE_, LOW);
  delay(10);
  digitalWrite(EEPROM_WE_, HIGH);
  delay(1);
  digitalWrite(EEPROM_CE_, HIGH);

}


/*
 * Read the contents of the EEPROM and print them to the serial monitor.
 */
void printContents(int len=2048) {
  for (int base = 0; base < len; base += 16) {
    byte data[16];
    for (int offset = 0; offset <= 15; offset += 1) {
      data[offset] = readEEPROM(base + offset);
    }

    char buf[80];
    sprintf(buf, "%03x:  %02x %02x %02x %02x %02x %02x %02x %02x   %02x %02x %02x %02x %02x %02x %02x %02x",
            base, data[0], data[1], data[2], data[3], data[4], data[5], data[6], data[7],
            data[8], data[9], data[10], data[11], data[12], data[13], data[14], data[15]);

    Serial.println(buf);
  }
}
// generated by xxd -i
unsigned char test_bin[] = {
  0x4c, 0x80, 0x7f, 0x4c, 0x83, 0x7f, 0xd8, 0xa2, 0xff, 0xba, 0xa9, 0x01,
  0xa2, 0x04, 0x95, 0x00, 0xe8, 0x2a, 0x90, 0xfa, 0xa9, 0x01, 0xa2, 0x04,
  0xd5, 0x00, 0x18, 0xd0, 0x07, 0xe8, 0x2a, 0x90, 0xf7, 0x4c, 0x8a, 0x7f,
  0x4c, 0xa4, 0x7f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x80, 0x7f, 0x86, 0x7f, 0x83, 0x7f
};
unsigned int test_bin_len = 128;

void setup() {
  // put your setup code here, to run once:
  pinMode(EEPROM_WE_, OUTPUT);
  pinMode(SHIFT_DATA, OUTPUT);
  pinMode(SHIFT_CLK, OUTPUT);
  pinMode(SHIFT_LATCH, OUTPUT);
  pinMode(EEPROM_CE_, OUTPUT);
  digitalWrite(EEPROM_WE_, HIGH);
  digitalWrite(EEPROM_CE_, HIGH);
  for (int pin = EEPROM_D0; pin <= EEPROM_D7; pin += 1) {
    pinMode(pin, INPUT_PULLUP);
  }

  Serial.begin(57600);

#if 1
// Erase entire EEPROM
  Serial.print("Erasing EEPROM");
  for (int address = 0; address <= 2047; address += 1) {
    writeEEPROM(address, 0xff);

    if (address % 64 == 0) {
      Serial.print(".");
    }
  }
  Serial.println(" done");
#endif

  int rom_len = 2048;
  char *rom_data;
  switch (ROM) {
      case 0:
          rom_data = _Users_w_warner_Library_Mobile_Documents_com_apple_CloudDocs_Missile_Command__missile_command_v3_035820_02_h1;
          break;
      case 1:
          rom_data = _Users_w_warner_Library_Mobile_Documents_com_apple_CloudDocs_Missile_Command__missile_command_v3_035821_02_jk1;
          break;
      case 2:
          rom_data = _Users_w_warner_Library_Mobile_Documents_com_apple_CloudDocs_Missile_Command__missile_command_v3_035825_02_r1;
          break;
      case 3:
          rom_data = _Users_w_warner_Library_Mobile_Documents_com_apple_CloudDocs_Missile_Command__missile_command_v3_035824_02_np1;
          break;
      case 4:
          rom_data = _Users_w_warner_Library_Mobile_Documents_com_apple_CloudDocs_Missile_Command__missile_command_v3_035823_02_ln1;
          break;
      case 5:
          rom_data = _Users_w_warner_Library_Mobile_Documents_com_apple_CloudDocs_Missile_Command__missile_command_v3_035822_03e_kl1;
          break;
      default:
          Serial.print("bad ROM index");
          return;
  }
#if 1
  // Program data bytes
  Serial.print("Programming EEPROM");
  for (int address = 0; address < rom_len; address += 1) {
      writeEEPROM(address, rom_data[address]);
      
      if (address % 64 == 0) {
          Serial.print(".");
      }
  }
  Serial.println(" done");
#endif

 #if 0
 // Read and print out the contents of the EERPROM
  Serial.println("Reading EEPROM");
  printContents();
 #endif
   // put your main code here, to run repeatedly:
  for (int i = 0; i < 1; i ++) {
    printContents();
  }

}


void loop() {
}
